apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    environment: lolo
    costCenter: lolo
    app: lolo
  name: ydf-app-demo-stage
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ydf-app-demo-stage
      app.kubernetes.io/name: ydf-app-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        podSecure: "true"
      labels:
        app.kubernetes.io/instance: ydf-app-demo-stage
        app.kubernetes.io/name: ydf-app-demo
    spec:
      containers:
      - image: nullck/kube-psp-python-app:1593549771
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: ydf-app-demo
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 80Mi
