apiVersion: v1
kind: Pod
metadata:
  name: pod-test
  namespace: qa
  annotations:
    podSecure: "true"
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 100
  containers:
    - image: busybox
      imagePullPolicy: IfNotPresent
      name: busybox
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 50m
          memory: 80Mi
