apiVersion: v1
kind: Pod
metadata:
  name: pod-test
  namespace: qa
spec:
  containers:
    - image: busybox
      imagePullPolicy: IfNotPresent
      name: busybox
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 50m
          memory: 80Mi
