kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: opa-validating-webhook
webhooks:
  - name: validating-webhook.openpolicyagent.org
    namespaceSelector:
      matchExpressions:
      - key: openpolicyagent.org/webhook
        operator: NotIn
        values:
        - ignore
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRRENmTXpUTWpvVUJEQU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05NakV3TVRBM01UazFNelEzV2hnUE1qSTVOREV3TWpNeE9UVXpORGRhTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU1xb0xpQ1h2WTlJSkYwaHR4aEEya3hBM1laN0dyWWxMWkt2dm1OWWlFM1JRVWNQNnU0Z2RSOXQKeWhPUXozbkRHdDhnZjVLTXN5M2JtYzBNL1JENWluc3dwZlBCSllvYW50M1BBUG9lYmw4aTZhUjlkY0x3SFA3Kwo5VnhnTnZIRFN3V0tISnJyYkxOWklOTVMwWCtWV0VXQk5HOWIzb2haMGplb0szR0ZMWWdvN2M4UlVjdEJjSWs0ClJ2ZWlzRWxDZVd4MjFWTllVcmxSMVBqQ2RibGNGVUVxa3RRalZPb1RqeC9YaTdxNklXVW9TYkxERlRRQTVkWjgKZUl0azU3M25NTmRGTU93NHVuY1ZodHRxU0V6WWhua2ZHQ1NJbjJIVlVMaFB0ZDVRaFJFY0J0a2JBQ01mVHlkMgpZL2VGMnFMNXEyaVJNTThyU2pTTUtnQzhvV3lERkpzQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCmNOdHgxZndwSWlBc0xsalBGTGh3NTI0YnNsUGdwL0RUMlNBclNFbTRmcXZDcjFXRmx2OEtlNGJlRjdtbmh0VWMKQ0xiUUtCTzlUaDBnMmlmdnZEb25TUzYrSFRuak0zRG1UbGh3bGY5azdKN1JoMUlrTWpRYWdpaTdLS0FLOFA0LwowQ08zeERkUTNRYWk3OFVQZzVmTFJXcXV6SnlTMlRRcE1yY3Z2NFAvbDllNXRUQmp3QlZLcEc2UkpqZGhMaW94ClEzWS9CemFvT0krMDFHOXhVM1NPNFdMNzJIWGZROFl6QkdpS1JoUk9uckY0VXc4SVRab3FCMnE3eExuUCsrYUgKVVFjTHRaZTFIS252Nk15Yk9ibWgvUW11M2EyQ3BoTWJQRTBEZmxseHYyK2RVV2ppVDdZUWxQWmlxSlBvOU5tcQpyMXJIb3p3ekhsYk93UG5kM2U4eXZBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        namespace: opa
        name: opa
